version: "3"

services:
  db_postgres:
    image: postgres:12
    volumes:
      - ./data/db_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - "5432:5432"

  ecommerce_app:
    tty: true
    build: .
    env_file:
      - .env
    volumes:
      - static:/code/static
      - .:/code
    command: >
      sh -c "python iati_project/manage.py makemigrations &&
             python iati_project/manage.py migrate &&
             python iati_project/manage.py loaddata alldata.json &&
             DJANGO_COLLECTSTATIC_NO_INPUT=1 python iati_project/manage.py collectstatic --noinput"

    depends_on:
      - db_postgres

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
    depends_on:
      - ecommerce_app

volumes:
  .:
  postgres_data:
  static:
