# Generated by Django 4.2.4 on 2023-08-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=250)),
                ('product_type_id', models.IntegerField()),
                ('main_color', models.IntegerField()),
                ('logo_color', models.IntegerField()),
                ('size', models.IntegerField()),
                ('has_sleeves', models.BooleanField()),
                ('photo_url', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
