# Generated by Django 4.2.4 on 2023-08-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_has_sleeves_alter_product_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
