# Generated by Django 4.2.4 on 2023-08-16 13:20

import apps.products.models
from django.db import migrations
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_color_compositionmaterial_material_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizing_type',
            field=enumchoicefield.fields.EnumChoiceField(default=apps.products.models.SizingType(3), enum_class=apps.products.models.SizingType, max_length=6),
        ),
    ]
