# Generated by Django 4.2.4 on 2023-08-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_sizing_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compositionmaterial',
            old_name='material_id',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='compositionmaterial',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='product_id',
            new_name='product',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Update date')),
                ('product_quantity', models.IntegerField()),
                ('current_date', models.DateTimeField(auto_now_add=True, verbose_name='Current date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
    ]
