# Generated by Django 4.2.4 on 2023-08-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_stock_inclusion_date_alter_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(editable=False, max_length=250),
        ),
    ]
