# Generated by Django 4.2.4 on 2023-08-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositionmaterial',
            name='percentage',
            field=models.IntegerField(null=True),
        ),
    ]
