# Generated by Django 4.2.4 on 2023-08-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_compositionmaterial_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='current_date',
            field=models.DateField(auto_now_add=True, verbose_name='Current date'),
        ),
    ]
