# Generated by Django 4.2.4 on 2023-08-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_cart_current_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
