# Generated by Django 4.2.4 on 2023-08-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_cart_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
