# Generated by Django 4.2.4 on 2023-08-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_deliver_cart_bought_alter_cart_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='current_stock',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='initial_stock',
            field=models.IntegerField(default=10),
        ),
    ]
